apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubeoperators.azenakhi.github.com
spec:
  group: azenakhi.github.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: kubeoperators
    singular: kubeoperator
    kind: KubeOperator
    shortNames:
      - ko
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - name
            - age
          properties:
            name:
              type: string
            age:
              type: integer