apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-operator
spec:
  selector:
    matchLabels:
      app: kube-operator
  template:
    metadata:
      labels:
        app: kube-operator
    spec:
      containers:
      - name: kube-operator
        image: docker.io/azenakhi/kube-operator:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
